apiVersion: v1
kind: Namespace
metadata:
  name: mcp-server
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mcp-server
type: Opaque
data:
  # admin
  username: YWRtaW4=
  # password
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
  namespace: mcp-server
data:
  ADDR: "0.0.0.0:8080"
  DB_NAME: "mcp_server"
  DEBUG: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: mcp-server
data:
  mongo-init.js: |
    // MongoDB initialization script
    db = db.getSiblingDB('mcp_server');
    
    // Create collections with proper indexes
    db.createCollection('documents');
    db.documents.createIndex({ "title": "text", "content": "text", "tags": "text" });
    db.documents.createIndex({ "created_at": -1 });
    db.documents.createIndex({ "tags": 1 });
    
    db.createCollection('search_cache');
    db.search_cache.createIndex({ "query": 1 });
    db.search_cache.createIndex({ "created_at": 1 }, { expireAfterSeconds: 3600 });
    
    print('MCP Server database initialized successfully');
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mcp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and modify for specific storage class
  # storageClassName: fast-ssd
